# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Tests

env:
  DOTNET_WORKINGDRIECTORY : 'test/dymaptic.GeoBlazor.Core.Test'

on:
  push:
    branches: [ "feature/automated_testing" ]
  pull_request:
    branches: [ "feature/automated_testing" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x
    - name: Restore dependencies   
      run: dotnet restore
      working-directory: ${{ env.DOTNET_WORKINGDRIECTORY }}
    - name: Build
      run: dotnet build --no-restore
      working-directory: ${{ env.DOTNET_WORKINGDRIECTORY }}
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ${{ env.DOTNET_WORKINGDRIECTORY }}
